# Generated by Django 4.0.2 on 2022-03-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedProduct',
            new_name='OrderProduct',
        ),
        migrations.RenameModel(
            old_name='OrderedStatus',
            new_name='OrderStatus',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='ordered_status',
            new_name='order_status',
        ),
        migrations.AlterModelTable(
            name='orderproduct',
            table='order_products',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='order_status',
        ),
    ]
