# Generated by Django 4.0.2 on 2022-03-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.discount'),
        ),
    ]
