# Generated by Django 4.0.2 on 2022-03-10 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_discount_subcategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFilteringOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defualt_filtering_options', models.TextField()),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
            ],
            options={
                'db_table': 'default_filtering_options',
            },
        ),
    ]
